### ISSUE TITLE
Accent功能追加

### ISSUE THREAD

**Issue by GavinLuo1985** [savent404/MX2#18]
# 功能说明
## 描述
- ### 文件路径
  0:\bank*\Accent\目录下
  Standby.txt
  On.txt
  Lockup.txt
  Clash.txt

- 控制文件位置如备注，若未读取到相关文件，则表示不执行

- ~~USR_CFG内需增加参数AccentLED=(0~8)，用于设置可控LED的个数~~

- USR_CFG内需增加参数LEDMASK, 用于设置哪些LED可以工作
    - 参数用16进制表示，每一位代表一个LED。
    - 16进制值的最低位对应LED1
    - 16进制->2进制后，每个`1`代表允许工作，`0`代表不工作
    - 实例： `LEDMASK=0x000F //(LED 1~4工作， 其余不工作)`

- 每个文件的单行周期T均可独立设置，亮灭控制最大256行
    - 为了兼容`UTF-8 with BOM` or `UTF-8 without BOM`, 文件第一行空行或写上注释文字

## Standby
待机状态下的小灯动作，若状态无变化则循环执行
## On
开机状态下的小灯动作，若状态无变化则循环执行
## Lockup
当'TriggerE'触发时同步执行，执行长同lockup(TriggerE),退回On时可抛弃未执行部分
## Clash
当'TriggerC'触发时同步执行，执行结束后返回On

**Comment by savent404** [comment]
# 执行反馈
由于有两个Accent LED占用了高速晶振输入口，强制使用为普通IO会导致无法进入Debug
缩减 8LED为6LED
目前文本文件中LED顺序逻辑与丝印对应情况

- 丝印8 -> LED0
- 丝印7 -> LED1
- 丝印4 -> LED2
- 丝印3 -> LED3
- 丝印2 -> LED4
- 丝印1 -> LED5
- 丝印0 -> LED6
